import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import { PageHeader } from 'antd';
import 'antd/dist/antd.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <PageHeader title="你过来呀！" onBack={() => null} />
    </>
  );
};
export default Home;
